### ISSUE TITLE
Error: Failed to parse user profile

### ISSUE THREAD

**Issue by danvass** [clocked0ne/passport-outlook#9]
@clocked0ne The library seems to be broken now after changes made to the outlook API. Even with `openid, profile, email` being added to the scope it's unable to load the profile from `/me`. The request always returns a 401.

**Comment by clocked0ne** [comment]
Hi @DVassilev do you know specifically what changes have been made to the API or have any more detail you could provide? I was not aware of this, but we have seen some erroneous responses lately from their API so I will try to look into this.

**Comment by danvass** [comment]
Hi @clocked0ne - I don't have too many details but from what I saw they've changed the scopes (for example, it seems you need `openid`, `profile` and `email` to be able to get the same profile details as before). Furthermore, they suggest taking out those details from the `id_token` passed through when you get the `access_token`. The `access_token` received seems to also no longer work for getting data from the profile url you have specified. As mention, it's always a 401. I didn't look too much into it though.

**Comment by clocked0ne** [comment]
Thanks that's helpful, I will do some local testing and see if I can resolve this.

**Comment by clocked0ne** [comment]
I cannot seem to recreate the issue. Providing these scopes:
```js
[ 'openid', 'email', 'profile', 'offline_access' ]
```
I receive the following json response, which is correctly parsed:
```js
{ Id: '<redacted>-0372-5b7b-0000-000000000000@<redacted>-e9f6-40af-b435-aaaaaaaaaaaa',
  EmailAddress: '<redacted>@outlook.com',
  DisplayName: '<redacted>',
  Alias: 'puid-0003BF<redacted>',
  MailboxGuid: '<redacted>-0372-5b7b-0000-000000000000' }
```

**Comment by danvass** [comment]
@clocked0ne That's odd, what response did you get when you request the access token? Interested to see what scope you were returned there. Also, how did you configure the app - what permissions did you set from the MS side in the application registration portal?

**Comment by clocked0ne** [comment]
From the Microsoft side the only additional permission set in scope is `https://outlook.office.com/Mail.ReadWrite`

The response gives all the scopes requested, though interestingly even if I don't specify `email` scope the profile still contains the email address

**Comment by clocked0ne** [comment]
There are no additional permissions (app or delegated) set in the app configuration from the MS side either, btw.

**Comment by clocked0ne** [comment]
@DVassilev Just catching up to see if you got to the bottom of this issue you were having?

**Comment by vgaltes** [comment]
Hi,

I'm facing the same issue. The app is asking me grant permissions to view the profile, etc, but when I click OK I see this error:

```
Error: Failed to parse user profile
    at Request._callback (/Users/itvga/Work/passport-outlook/examples/login/node_modules/passport-outlook/lib/strategy.js:144:19)
    at Request.self.callback (/Users/itvga/Work/passport-outlook/examples/login/node_modules/request/request.js:186:22)
    at Request.emit (events.js:127:13)
    at Request.<anonymous> (/Users/itvga/Work/passport-outlook/examples/login/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:127:13)
    at IncomingMessage.<anonymous> (/Users/itvga/Work/passport-outlook/examples/login/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:219:13)
    at IncomingMessage.emit (events.js:132:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

I'm using the code in the examples folder with my own keys.

Thanks

**Comment by clocked0ne** [comment]
@vgaltes can you add `console.log(body);`at line 140 of:
`/Users/itvga/Work/passport-outlook/examples/login/node_modules/passport-outlook/lib/strategy.js`

Then we can see what is coming back in the response that is not parsing correctly.

**Comment by vgaltes** [comment]
Thanks for you response @clocked0ne It looks like I'm getting a 401...

```
RES: {"statusCode":401,"body":"","headers":{"set-cookie":["exchangecookie=49666678eaef4351acbd4b5686e2085a; expires=Wed, 10-Apr-2019 21:18:49 GMT; path=/; HttpOnly"],"www-authenticate":"Bearer client_id=\"00000002-0000-0ff1-ce00-000000000000\", trusted_issuers=\"00000001-0000-0000-c000-000000000000@*\", token_types=\"app_asserted_user_v1 service_asserted_app_v1\", authorization_uri=\"https://login.windows.net/common/oauth2/authorize\", error=\"invalid_token\",Basic Realm=\"\",Basic Realm=\"\"","request-id":"aec0dc9f-701a-46ac-b482-d37b15b72408","x-calculatedbetarget":"PR2P264MB0735.FRAP264.PROD.OUTLOOK.COM","x-backendhttpstatus":"401","x-ms-diagnostics":"2000001;reason=\"OAuth token submitted with the request can not be parsed.\";error_category=\"invalid_token\"","x-diaginfo":"PR2P264MB0735","x-beserver":"PR2P264MB0735","x-powered-by":"ASP.NET","x-feserver":"PR2P264CA0040","x-msedge-ref":"Ref A: 085A347E5FF74D3DAEA16DD4763A865B Ref B: PAR02EDGE0511 Ref C: 2018-04-10T21:18:49Z","date":"Tue, 10 Apr 2018 21:18:48 GMT","connection":"close","content-length":"0"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"outlook.office.com","port":443,"hostname":"outlook.office.com","hash":null,"search":null,"query":null,"pathname":"/api/v2.0/me","path":"/api/v2.0/me","href":"https://outlook.office.com/api/v2.0/me"},"method":"GET","headers":{"Authorization":"Bearer undefined","Accept":"application/json; odata.metadata=none"}}}
err: null
BODY: ""
```

Is strange because this was working a couple of months ago...

**Comment by clocked0ne** [comment]
Have you checked that your client ID and secret are correct?

**Comment by zbrukas** [comment]
Could it be Graph permissions for the scopes you're requiring?

**Comment by darkmeton** [comment]
It seems if you add the `https://outlook.office.com/Mail.ReadWrite` permission it works. But I don't want to manage my user's emails, just get his basic profile info

**Comment by clocked0ne** [comment]
@darkmeton Are you experiencing the same issue as @DVassilev - 401s returned?

**Comment by babotaemin** [comment]
Hi, I'm facing the same issue too. T.T.
console.log(body) ----> blank.
console.log(res.statusCode) -----> 401 returned.

**Comment by clocked0ne** [comment]
@babotaemin and anyone else, can you confirm if you are using scopes, that any of the API specific scopes you are using are fully qualified to match the outlook domain, e.g: `https://outlook.office.com/Mail.Read` instead of `Mail.Read`

This is very important, otherwise you will receive 401 responses

**Comment by knassik** [comment]
Hi @clocked0ne,

I had the same issue, I added "https://outlook.office.com/Mail.Read" to the scope list as you said and it worked, thank you.

**Comment by kehers** [comment]
Note: According to the docs, `outlook.office.com/Mail.read` will give you a REST access token and not a graph access token. `Mail.Read` grants access to the graph API

**Comment by kehers** [comment]
For everyone still experiencing issue with this (and interested in the Graph API), 
1. Update your scopes to include `User.Read`
2. `Use 'https://graph.microsoft.com/v1.0/me` as your `userProfileURL`

```
  passport.use('outlook', new OutlookStrategy({
    clientID: ID, clientSecret: SECRET, callbackURL: CB,
    userProfileURL: 'https://graph.microsoft.com/v1.0/me?$select=userPrincipalName'
  }, (accessToken, refreshToken, profile, done) => {
        // ...
    }
  ));

  router.get('/cb', passport.authenticate('outlook', {
      scope: ['offline_access', 'User.Read', 'Mail.Read', 'Mail.Send']
  }));
```

**Comment by clocked0ne** [comment]
@kehers  The two are distinct, yes, the Graph API is the replacement for the now deprecated Outlook REST API v2 but you must ensure your application is registered to use the Graph API. That's my understanding at least, my team haven't migrated our own application yet.
